### ISSUE TITLE
New issue after HA upgrade to 2023.8.1

### ISSUE THREAD

**Issue by sylwesterr** [NECH2004/zeversolar_local#11]
The integration stopped working and in the HA log I can see:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: August 7, 2023 at 7:08:41 PM (10 occurrences)
Last logged: 12:01:27 PM

    Error adding entities for domain sensor with platform zeversolar_local
    Error while setting up zeversolar_local platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'has_entity_name'

**Comment by NECH2004** [comment]
has_entity_name is an unknown field. I think I've made a copy/paste error. Fixed in version 1.2.1

**Comment by sylwesterr** [comment]
It's aliiiiiive!!! thanks :)
