### ISSUE TITLE
Restart HA with offline zeversolar

### ISSUE THREAD

**Issue by phoenix-blue** [NECH2004/zeversolar_local#6]
Is it possible to made an option that the integration after an reboot of HA with an inverter that is offline an poll timer that it's try (until the zever solar is online) to turn on the integration.

Now it give an error after an reboot when the zeversolar is offline and is the next day not automatically reset this error. 

2022-09-07 22:01:50.942 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Zeversolar Inverter for zeversolar_local

**Comment by NECH2004** [comment]
I'll fix this behavior. Disable and re-enable the integration when the inverter is online will it bring back to live but it is not what I have had in mind. Hope that I am able to do that in time.

**Comment by NECH2004** [comment]
Will be fixed in v1.2.0

**Comment by NECH2004** [comment]
Fixed in v1.2.0

**Comment by phoenix-blue** [comment]
Thx, I have updated to this verion.

Op zo 11 sep. 2022 13:23 schreef Christian Neumeier <
***@***.***>:
