### ISSUE TITLE
Can't Select 'Zeversolar Current Power' in Energy Dashboard under 

### ISSUE THREAD

**Issue by molis83** [NECH2004/zeversolar_local#7]
First of all: Thank you for your wonderfull work!

The installation of the integration was very easy!

I wanted to add the Zeversolar system to the Energy Dashboard, but I can only select 'Zeversolar Inverter Total energy Today as entity. I would expect te Current Power entity over there.

 
![Screenshot 2022-10-21 150203](https://user-images.githubusercontent.com/6142487/197202044-bdbb3675-e776-4fc0-ac52-bd49a79735fb.png)

**Comment by sylwesterr** [comment]
It is ok to use "Total energy Today" - that's how Energy Panel in HA works. Please mind that it takes around an hour for the hourly measurements to show on the power chart.

**Comment by NECH2004** [comment]
HA only allows to select the energy entities not the power entities. Because HA did not change the behaviour I'll close that issue.

**Comment by sylwesterr** [comment]
I was using THIS entity molis83 pointed for almost a year now, with success. Recently, after upgrading to 2023.8.1, the integration stopped working completely (see the issue I opened), so had to switch to "native" integration available in HA "integrations store", and also chose the same type of entity for Energy panel and after an hour it started showing in the Energy panel, so "this is the way" :)
